name: fastcan-rtd
channels:
  - conda-forge
dependencies:
  - micromamba
  - pip
  - furo
  - sphinx-gallery
  - sphinx-design
  - sphinxcontrib-plantuml
  - jupyterlite-sphinx
  - plantuml
  - pip:
      - .
      - jupyterlite-xeus